"""empty message

Revision ID: 173bdaa26a22
Revises: 92e300249ffd
Create Date: 2023-11-22 23:29:27.105235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173bdaa26a22'
down_revision: Union[str, None] = '92e300249ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
