"""empty message

Revision ID: 1c3db6a23f8b
Revises: 5646733384cd
Create Date: 2024-07-04 21:51:44.231514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3db6a23f8b'
down_revision: Union[str, None] = '5646733384cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'tiktok')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('tiktok', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
